version: '3.3'

services:

  hoaxy:
    image: hoaxy-backend:miniconda2-jdk8-alpine3.9
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
      HOAXY_HOME: /home/.hoaxy
      HOST: localhost
      PORT: 8080
    volumes:
    - ./docker/shared/config/hoaxy:/home/.hoaxy
    - ./docker/shared/docker/lucene:/var/lib/data/lucene
    stdin_open: true
    tty: true

  postgres:
    image: postgres:9.6-alpine
    # restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: hoaxy
      POSTGRES_USER: hoaxy
      POSTGRES_DB: hoaxy
    volumes:
    - ./docker/shared/docker/postgresql:/var/lib/postgresql

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
